name: Build Wasm component

on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x

      - name: Setup wash CLI
        uses: cosmonic-labs/setup-wash-action@main
        with:
          wash-version: 1.0.0-beta.6


      - name: Compile Wasm binary and capture component path
        id: build
        run: |
          set -e

          artifact_path=$(wash build --output json | jq -r .data.artifact_path)
          if [ -z "$artifact_path" ] || [ "$artifact_path" = "null" ]; then
            echo "Failed to determine built component path" >&2
            exit 1
          fi
          echo "component_path=$artifact_path" >> $GITHUB_OUTPUT

      - name: Verify Wasm binary exists
        run: |
          if [ ! -f "${{ steps.build.outputs.component_path }}" ]; then
            echo "Error: ${{ steps.build.outputs.component_path }} not found!" >&2
            exit 1
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Wasm component to ghcr.io
        run: |
          wash oci push ghcr.io/${GITHUB_REPOSITORY,,}:${{ github.ref_name }} "${{ steps.build.outputs.component_path }}"
